services:

  vectorStoreAPI:
      build:
      context: .
      dockerfile: Dockerfile

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data:/qdrant/storage
