services:

  copyrighteous:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEVICE: cpu
      MONGO_ADDRESS: mongo:27017/
      QDRANT_ADDRESS: http://qdrant
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./data/videos:/data/videos
      - ./data/cache:/root/.cache
      - ./models:/models
    stdin_open: true 
    tty: true   
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  mongo:
    image: mongo:8.0.0-rc7-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  qdrant:
    image: qdrant/qdrant:v1.9.4
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage


